### ISSUE TITLE
control-box-lid-v.1.0.stl is empty

### ISSUE THREAD

**Issue by prausch** [FourThievesVinegar/Parts#4]
I'm assuming that the control-box-lid-v.1.0.stl is the lid that fits on the control-box-v.1.1.stl box. It's easier for me to print this shape box in two parts (Prusa MINI+), so it would be great to have a lid that fit it.

This file in the repository is empty.

**Comment by sparklestheunicorn** [comment]
This should be resolved now. Thanks for the heads up.
